#!/usr/bin/env bash -x

haversine() {
  LAT_FN=1 LON_FN=2 WALK_FN=9 ruby -nF";" haversine.rb
}

walks() {
  awk 'BEGIN{FS=";"; count=0} {if ($NF >= 3600) {count++} print $0 FS count}'
}

time_difference() {
  awk 'BEGIN{FS=";"} {print $1}' | ./time_difference
}

temp_fifo() {
local f=$(mktemp -u)
mkfifo -m 777 "$f"
echo $f
}


base=$(temp_fifo)
time_diff=$(temp_fifo)

cat big.csv | tail -n+2 | tee $base | time_difference | tee $time_diff | head -n 4 & $base #tee $time_diff  & paste $time_diff | head -n 5 
cat $base | head -n 1

#cat big.csv | tail -n+2  | awk 'BEGIN{FS=";"} {print $1}' | ./time_difference #| walks | haversine 
#cat big.csv | tail -n+2  | awk 'BEG./time_difference #| walks | haversine 
