#!/bin/sh -eu

time_difference() {
  TIME_FN=0 ruby -nF";" time_difference.rb
}

haversine() {
  LAT_FN=1 LON_FN=2 WALK_FN=10 =ruby -nF";" haversine.rb
}

walks() {
  awk 'BEGIN{FS=";"; count=0} {if (NF >= 3600) {count++} print $0 FS count}'
}

cat gps_dataset.csv | tail -n+2  | time_difference | walks | haversine 
