#!/usr/bin/env ruby -n -F;
require 'chronic'
BEGIN { last = nil }

fields = $_.split($F)
if !last
  last = Chronic.parse(fields[0])
end

difference = Chronic.parse(fields[0]) - last
last = Chronic.parse(fields[0])
puts "#{difference}; #{$_}"
