#!/usr/bin/env ruby -nF;
require 'chronic'
BEGIN { last = nil }
puts $F
fields = $_.split($F)
if !last
  last = Chronic.parse(fields[0])
end

difference = Chronic.parse(fields[0]) - last
last = Chronic.parse(fields[0])
puts "#{difference}#{$F} #{$_}"
